language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install coveralls
env:
  - DB=sqlite
branches:
  only:
    - develop
    - tests
    - features
script:
- nosetests --rednose --with-coverage --cover-package=app
after_success: coveralls
cache: pip
notifications:
  email: cynthia.abura@andela.com
